# Generated by Django 4.0.6 on 2022-07-11 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('studentId', models.IntegerField()),
                ('roomtype', models.CharField(blank=True, choices=[('FOUR IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE', 'FOUR IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE'), ('TWO IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE', 'TWO IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE'), ('TWO IN A ROOM SELF-CONTAIN WITH KITCHEN AND HALL', 'TWO IN A ROOM SELF-CONTAIN WITH KITCHEN AND HALL'), ('TWO IN A ROOM SELF-CONTAIN WITH CHAMBER AND HALL', 'TWO IN A ROOM SELF-CONTAIN WITH CHAMBER AND HALL')], max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=6)),
                ('room_choosing_status', models.CharField(choices=[('Manual room Selection', 'Manual room Selection'), ('Automatic room allocation', 'Automatic room allocation')], max_length=50)),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('capacity', models.IntegerField(default=0)),
                ('roomtype', models.CharField(blank=True, choices=[('FOUR IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE', 'FOUR IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE'), ('TWO IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE', 'TWO IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE'), ('TWO IN A ROOM SELF-CONTAIN WITH KITCHEN AND HALL', 'TWO IN A ROOM SELF-CONTAIN WITH KITCHEN AND HALL'), ('TWO IN A ROOM SELF-CONTAIN WITH CHAMBER AND HALL', 'TWO IN A ROOM SELF-CONTAIN WITH CHAMBER AND HALL')], max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=6)),
                ('full', models.BooleanField(default=False)),
                ('people', models.ManyToManyField(blank=True, to='berlApp.detaileduser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
