# Generated by Django 4.0.5 on 2022-07-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berlApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bookings', models.ManyToManyField(blank=True, to='berlApp.detaileduser')),
            ],
        ),
        migrations.RemoveField(
            model_name='mroom2mw',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mroom3mw',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mroom4mw',
            name='name',
        ),
        migrations.DeleteModel(
            name='MRoom1mw',
        ),
        migrations.DeleteModel(
            name='MRoom2mw',
        ),
        migrations.DeleteModel(
            name='MRoom3mw',
        ),
        migrations.DeleteModel(
            name='MRoom4mw',
        ),
    ]
