# Generated by Django 4.0.5 on 2022-07-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berlApp', '0002_room_remove_mroom2mw_name_remove_mroom3mw_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaileduser',
            name='roomtype',
        ),
    ]
