# Generated by Django 4.0.5 on 2022-07-11 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('berlApp', '0003_remove_detaileduser_roomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bookings',
            new_name='people',
        ),
        migrations.AddField(
            model_name='detaileduser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detaileduser',
            name='roomtype',
            field=models.CharField(blank=True, choices=[('FOUR IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE', 'FOUR IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE'), ('TWO IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE', 'TWO IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE'), ('TWO IN A ROOM SELF-CONTAIN WITH KITCHEN AND HALL', 'TWO IN A ROOM SELF-CONTAIN WITH KITCHEN AND HALL'), ('TWO IN A ROOM SELF-CONTAIN WITH CHAMBER AND HALL', 'TWO IN A ROOM SELF-CONTAIN WITH CHAMBER AND HALL')], max_length=120),
        ),
        migrations.AddField(
            model_name='detaileduser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=6),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detaileduser',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
