# Generated by Django 4.0.5 on 2022-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berlApp', '0004_rename_bookings_room_people_detaileduser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaileduser',
            name='room_choosing_status',
            field=models.CharField(choices=[('Automatic room allocation', 'Automatic room allocation'), ('Manual room Selection', 'Manual room Selection')], max_length=50),
        ),
    ]
