# Generated by Django 4.0.5 on 2022-07-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berlApp', '0005_alter_detaileduser_room_choosing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomtype',
            field=models.CharField(blank=True, choices=[('FOUR IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE', 'FOUR IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE'), ('TWO IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE', 'TWO IN A ROOM SELF-CONTAIN WITH BALCONY KICHENNETTE'), ('TWO IN A ROOM SELF-CONTAIN WITH KITCHEN AND HALL', 'TWO IN A ROOM SELF-CONTAIN WITH KITCHEN AND HALL'), ('TWO IN A ROOM SELF-CONTAIN WITH CHAMBER AND HALL', 'TWO IN A ROOM SELF-CONTAIN WITH CHAMBER AND HALL')], max_length=120),
        ),
        migrations.AlterField(
            model_name='detaileduser',
            name='room_choosing_status',
            field=models.CharField(choices=[('Manual room Selection', 'Manual room Selection'), ('Automatic room allocation', 'Automatic room allocation')], max_length=50),
        ),
    ]
